# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --no-restore --configuration Release
    
    - name: Test with Code Coverage
      run: dotnet test --no-build --configuration Release --verbosity normal --filter "TestCategory!=Integration" --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Convert coverage to Cobertura format
      run: |
        mkdir -p TestResults
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:TestResults -reporttypes:Cobertura

    - name: Upload Code Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: TestResults/

    - name: Pack Nuget Package
      run: dotnet pack --configuration Release --output Nupkgs

    - name: Upload Shellscripts OpenEHR Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: shellscripts-openehr-package
        path: ./Nupkgs/*.nupkg
