# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test and Code Coverage
      run: dotnet test --no-build --verbosity normal --filter "TestCategory!=Integration" --collect:"XPlat Code Coverage"

    - name: Convert coverage to Cobertura format
      run: |
        mkdir -p TestResults
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:TestResults -reporttypes:Cobertura

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: TestResults/
